package com.example.think.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.think.database.ChannelEntity;

import com.example.think.greendao.ChannelEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelEntityDaoConfig;

    private final ChannelEntityDao channelEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelEntityDaoConfig = daoConfigMap.get(ChannelEntityDao.class).clone();
        channelEntityDaoConfig.initIdentityScope(type);

        channelEntityDao = new ChannelEntityDao(channelEntityDaoConfig, this);

        registerDao(ChannelEntity.class, channelEntityDao);
    }
    
    public void clear() {
        channelEntityDaoConfig.clearIdentityScope();
    }

    public ChannelEntityDao getChannelEntityDao() {
        return channelEntityDao;
    }

}
